import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google";
import { Fraunces } from "next/font/google";
import "./globals.css";

const BodyFont = Darker_Grotesque({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const HeadingFont = Fraunces({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${BodyFont.className} ${HeadingFont.className}`}>
        {children}
      </body>
    </html>
  );
}
